"""empty message

Revision ID: 06d055277ebf
Revises: e509f419900d
Create Date: 2021-06-17 04:02:08.792237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d055277ebf'
down_revision = 'e509f419900d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant', sa.Column('is_viewed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicant', 'is_viewed')
    # ### end Alembic commands ###
