"""empty message

Revision ID: 5b33f01f15e3
Revises: ac750319e0fd
Create Date: 2021-05-17 03:20:38.591798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b33f01f15e3'
down_revision = 'ac750319e0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture_path')
    # ### end Alembic commands ###
