"""empty message

Revision ID: a56cacf0915b
Revises: 3ddc4bce10bc
Create Date: 2021-05-28 15:44:00.093741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56cacf0915b'
down_revision = '3ddc4bce10bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('color', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'color')
    # ### end Alembic commands ###
