"""empty message

Revision ID: eaf8d112e400
Revises: a56cacf0915b
Create Date: 2021-05-28 15:57:23.358464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eaf8d112e400'
down_revision = 'a56cacf0915b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal', 'topic_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('journal_ibfk_1', 'journal', type_='foreignkey')
    op.create_foreign_key(None, 'journal', 'topic', ['topic_id'], ['id'], ondelete='SET NULL')
    op.alter_column('journal_log', 'status_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('journal_log_ibfk_3', 'journal_log', type_='foreignkey')
    op.drop_constraint('journal_log_ibfk_2', 'journal_log', type_='foreignkey')
    op.create_foreign_key(None, 'journal_log', 'status', ['status_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'journal_log', 'reviewer', ['reviewer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal_log', type_='foreignkey')
    op.drop_constraint(None, 'journal_log', type_='foreignkey')
    op.create_foreign_key('journal_log_ibfk_2', 'journal_log', 'reviewer', ['reviewer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('journal_log_ibfk_3', 'journal_log', 'status', ['status_id'], ['id'], ondelete='CASCADE')
    op.alter_column('journal_log', 'status_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'journal', type_='foreignkey')
    op.create_foreign_key('journal_ibfk_1', 'journal', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    op.alter_column('journal', 'topic_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
